spring:
  datasource:
    url: jdbc:h2:mem:vehicle;INIT=CREATE SCHEMA IF NOT EXISTS vehicle
    username: vehicle-user
    password: vehicle-pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true